spring.application.name=booking-service
spring.profiles.active=${ACTIVE_PROFILE}
jwt.secret=${JWT_SECRET}

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/booking_service
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings (JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# Liquibase Configuration
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# OpenAPI/Swagger configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true

# Custom API documentation
springdoc.api-docs.groups.enabled=true