spring.application.name=lesson-booking-service

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/lesson_booking
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings (JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
